version: '3.7'
services:
  some-app:
    container_name: some-app
    restart: always
    command: tail -f /dev/null
    volumes:
      - ./app:/app
    build:
      context: app
      dockerfile: ./Dockerfile
    ports:
      - 5057:5057
    networks:
      - some-app_network

networks:
  some-app_network: